from pathlib import Path
import importlib.util
import os
import re
import shutil


ROOT = Path(__file__).resolve().parents[2]
HERE = Path(__file__).resolve().parent
OLD_TEXT = ROOT / "Pokemblem-Text1.20"
CURRENT_TEXT = ROOT / "Text"
DUMP = HERE / "chinese.txt"
OUT = HERE / "text_buildfile.txt"


def load_text_process():
    path = ROOT / "Tools" / "TextProcess" / "text-process-classic.py"
    spec = importlib.util.spec_from_file_location("text_process_classic", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def load_entries(text_process, buildfile):
    previous = Path.cwd()
    os.chdir(buildfile.parent)
    try:
        lines = text_process.Preprocessor(False).preprocess(buildfile.name)
        return list(text_process.generate_text_entries(lines, False))
    finally:
        os.chdir(previous)


def load_dump():
    entries = {}
    current_id = None
    current_lines = []
    header = re.compile(r"\[([0-9A-Fa-f]+)\]")

    for line in DUMP.read_text(encoding="utf-8", errors="replace").splitlines():
        match = header.fullmatch(line.strip())
        if match:
            if current_id is not None:
                entries[current_id] = "\n".join(current_lines)
            current_id = int(match.group(1), 16)
            current_lines = []
        else:
            current_lines.append(line)

    if current_id is not None:
        entries[current_id] = "\n".join(current_lines)

    return entries


def dump_text_to_source(raw):
    text = raw.replace("\r\n", "\n").replace("\r", "\n").strip("\n")
    text = text.replace("\x1f", "[X]")
    text = text.replace("[FastPrint2]", "[FastPrint]")
    text = re.sub(
        r"\[LoadFace\]\[0x([0-9A-Fa-f]{3,})\]",
        lambda match: f"[LoadFace][0x{int(match.group(1), 16) & 0xFF:X}][0x{int(match.group(1), 16) >> 8:X}]",
        text,
    )

    if text.endswith("[X]"):
        text = text[:-3]

    lines = text.split("\n") if text else [""]
    source = "[N]\n".join(lines)
    return source + "[X]"


def comparable(text):
    return text.replace("\r\n", "\n").replace("\r", "\n").strip()


def has_useful_translation(source, old_source):
    if not source or source == "[X]":
        return False

    if comparable(source) != comparable(old_source):
        return True

    return any(ord(ch) > 0x7F for ch in source)


def main():
    text_process = load_text_process()
    old_entries = load_entries(text_process, OLD_TEXT / "text_buildfile.txt")
    current_entries = load_entries(text_process, CURRENT_TEXT / "text_buildfile.txt")
    dump_entries = load_dump()

    current_by_definition = {
        entry.definition: entry
        for entry in current_entries
        if entry.definition
    }
    current_numeric = {
        entry.stringId: entry
        for entry in current_entries
        if not entry.definition
    }

    generated = {}
    mapped_by_definition = 0
    mapped_by_number = 0
    skipped_missing_current = 0
    skipped_missing_dump = 0
    skipped_unchanged = 0

    for old_entry in old_entries:
        raw = dump_entries.get(old_entry.stringId)
        if raw is None:
            skipped_missing_dump += 1
            continue

        source = dump_text_to_source(raw)
        if not has_useful_translation(source, old_entry.text):
            skipped_unchanged += 1
            continue

        if old_entry.definition:
            current_entry = current_by_definition.get(old_entry.definition)
            if current_entry is None:
                skipped_missing_current += 1
                continue

            generated[current_entry.stringId] = (current_entry.definition, source)
            mapped_by_definition += 1
            continue

        current_entry = current_numeric.get(old_entry.stringId)
        if current_entry is None:
            skipped_missing_current += 1
            continue

        if comparable(current_entry.text) != comparable(old_entry.text):
            skipped_missing_current += 1
            continue

        generated[current_entry.stringId] = (None, source)
        mapped_by_number += 1

    lines = [
        "// Generated by extract_chinese_text.py.",
        "// Source dump: Language/Chinese/chinese.txt from Pokemblem_Chinese1.20.gba.",
        "// Labels are mapped from Pokemblem-Text1.20 to the current Text table where possible.",
        "",
    ]

    for text_id, (definition, source) in sorted(generated.items()):
        if definition:
            lines.append(f"# 0x{text_id:03X} {definition}")
        else:
            lines.append(f"# 0x{text_id:03X}")
        lines.append(source)
        lines.append("")

    OUT.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    shutil.copyfile(CURRENT_TEXT / "ParseDefinitions.txt", HERE / "ParseDefinitions.txt")

    print(f"wrote {OUT.relative_to(ROOT)}")
    print(f"mapped by definition: {mapped_by_definition}")
    print(f"mapped by stable numeric id: {mapped_by_number}")
    print(f"skipped missing current slot: {skipped_missing_current}")
    print(f"skipped missing dump entry: {skipped_missing_dump}")
    print(f"skipped unchanged dump text: {skipped_unchanged}")


if __name__ == "__main__":
    main()
